site_name: Icon Generation
nav:
- 'Home': 'index.md'
- 'Project Information': 'project_info.md'
- 'Shape Approximation': 'image_approx.md'
- 'Previous approaches': 'prev_approaches.md'
- 'About': 'about.md'
theme: 'material'
